# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 714)
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/maps_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("font-size:20px;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(100, 10, 601, 451))
        self.image.setStyleSheet("background-color:#ccc;")
        self.image.setText("")
        self.image.setObjectName("image")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 470, 801, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(200, 20, 200, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_latitude = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_latitude.setObjectName("label_latitude")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_latitude)
        self.doubleSpinBox_latitude = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.doubleSpinBox_latitude.setDecimals(5)
        self.doubleSpinBox_latitude.setMinimum(-90.0)
        self.doubleSpinBox_latitude.setMaximum(90.0)
        self.doubleSpinBox_latitude.setSingleStep(0.1)
        self.doubleSpinBox_latitude.setObjectName("doubleSpinBox_latitude")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_latitude)
        self.label_longitude = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_longitude.setObjectName("label_longitude")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_longitude)
        self.doubleSpinBox_longitude = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.doubleSpinBox_longitude.setDecimals(5)
        self.doubleSpinBox_longitude.setMinimum(-180.0)
        self.doubleSpinBox_longitude.setMaximum(180.0)
        self.doubleSpinBox_longitude.setSingleStep(0.1)
        self.doubleSpinBox_longitude.setObjectName("doubleSpinBox_longitude")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_longitude)
        self.label_scale = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_scale.setObjectName("label_scale")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_scale)
        self.doubleSpinBox_scale = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.doubleSpinBox_scale.setDecimals(5)
        self.doubleSpinBox_scale.setMaximum(90.0)
        self.doubleSpinBox_scale.setSingleStep(0.1)
        self.doubleSpinBox_scale.setObjectName("doubleSpinBox_scale")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_scale)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 610, 231, 61))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Yandex.Maps API"))
        self.label_latitude.setText(_translate("MainWindow", "Latitude                  "))
        self.label_longitude.setText(_translate("MainWindow", "Longitude"))
        self.label_scale.setText(_translate("MainWindow", "Scale"))
        self.pushButton.setText(_translate("MainWindow", "Create static map"))
